ACTORS = {
    "Actor": "Actor",
    "Creature": "Creature",
    "NPC": "NPC",
    "Player": "Player",
    "DummyPlayer": "DummyPlayer",
    "HostedPlayerActor": "HostedPlayerActor",
    "PlayerCorpse": "PlayerCorpse",
    "PU_NPC": "NPC",
    "PU_Human-Advocacy-Agent-Female-OpenHelmet": "Advocacy Agent OpenHelmet",
    "PU_Human-Advocacy-Agent-Male-OpenHelmet": "Advocacy Agent OpenHelmet",
    "PU_Human-BlacJac-Guard-Male-Grunt": "BlacJac Guard Grunt",
    "PU-Human-Bounty_Easy": "Bounty Easy",
    "PU-Human-Bounty_EndGame": "Bounty EndGame",
    "PU-Human-Bounty_EndGame_Rare": "Bounty EndGame Rare",
    "PU-Human-Bounty_Hard": "Bounty Hard",
    "PU-Human-Bounty_Medium": "Bounty Medium",
    "PU-Human-Bounty_Medium_Rare": "Bounty Medium Rare",
    "PU-Human-Bounty_Super": "Bounty Super",
    "PU-Human-Bounty_Very_Easy": "Bounty Very Easy",
    "PU-Human-Bounty_Very_Hard": "Bounty Very Hard",
    "PU-Human-Bounty_Very_Hard_Rare": "Bounty Very Hard Rare",
    "PU_Human-Aciedo-Male-Security-Grunt": "Aciedo Security Grunt",
    "PU_Human-Crusader-Admin-Female-InfoDesk": "Crusader Admin InfoDesk",
    "PU_Human-Crusader-Admin-Male-Orison": "Crusader Admin",
    "PU_Human-Crusader-Engineer-Female-Orison_StarlinerCrew": "Crusader Engineer Orison StarlinerCrew",
    "PU_Human-Crusader-Engineer-Male-Orison_StarlinerCrew": "Crusader Engineer Orison StarlinerCrew",
    "PU_Human-Crusader-Greeter-Male-Lobby": "Crusader Greeter Lobby",
    "PU_Human-Crusader-Guard-Male-Orison_Security": "Crusader Guard Orison Security",
    "PU_Human-Crusader-Boss-Male-Boss": "Crusader Boss",
    "PU_Human-Crusader-SuperBoss-Male-Kareah_Boss": "Crusader SuperBoss Kareah Boss",
    "PU_Human-Crusader-Guard-Female-Heavy": "Crusader Guard Heavy",
    "PU_Human-Crusader-Guard-Female-Light": "Crusader Guard Light",
    "PU_Human-Crusader-Guard-Female-Medium": "Crusader Guard Medium",
    "PU_Human-Crusader-Guard-Female-Orison_Security": "Crusader Guard Orison Security",
    "PU_Human-Crusader-Guard-Male-Beachhead_Heavy": "Crusader Guard Beachhead Heavy",
    "PU_Human-Crusader-Guard-Male-Beachhead_Light": "Crusader Guard Beachhead Light",
    "PU_Human-Crusader-Guard-Male-Beachhead_Medium": "Crusader Guard Beachhead Medium",
    "PU_Human-Crusader-Guard-Male-Grunt": "Crusader Guard Grunt",
    "PU_Human-Crusader-Guard-Male-Heavy": "Crusader Guard Heavy",
    "PU_Human-Crusader-Guard-Male-Light": "Crusader Guard Light",
    "PU_Human-Crusader-Guard-Male-Light_OneTime": "Crusader Guard Light OneTime",
    "PU_Human-Crusader-Guard-Male-Medium": "Crusader Guard Medium",
    "PU_Human-Crusader-Shopkeep-Female-Showroom_Clerk": "Crusader Shopkeep Showroom Clerk",
    "PU_Human-Crusader-Shopkeep-Female-Showroom_Salesperson": "Crusader Shopkeep Showroom Salesperson",
    "PU_Human-Crusader-Shopkeep-Male-Showroom_Salesperson": "Crusader Shopkeep Showroom Salesperson",
    "PU_Human-Crusader-Worker-Female-Kareah_Detective": "Crusader Worker Kareah Detective",
    "PU_Human-Crusader-Worker-Male-Kareah_Detective": "Crusader Worker Kareah Detective",
    "PU_Human-Covalex-DeskWorker-Female-DistroHub_Administrator": "Covalex DeskWorker DistroHub Administrator",
    "PU_Human-Covalex-DeskWorker-Female-DistroHub_Civilian": "Covalex DeskWorker DistroHub Civilian",
    "PU_Human-Covalex-DeskWorker-Female-DistroHub_OfficeWorker": "Covalex DeskWorker DistroHub OfficeWorker",
    "PU_Human-Covalex-DeskWorker-Female-DistroHub_Vendor": "Covalex DeskWorker DistroHub Vendor",
    "PU_Human-Covalex-DeskWorker-Male-DistroHub_Administrator": "Covalex DeskWorker DistroHub Administrator",
    "PU_Human-Covalex-DeskWorker-Male-DistroHub_Civilian": "Covalex DeskWorker DistroHub Civilian",
    "PU_Human-Covalex-DeskWorker-Male-DistroHub_OfficeWorker": "Covalex DeskWorker DistroHub OfficeWorker",
    "PU_Human-Covalex-DeskWorker-Male-DistroHub_Vendor": "Covalex DeskWorker DistroHub Vendor",
    "PU_Human-Covalex-Worker-Female-DistroHub_Engineer": "Covalex Worker DistroHub Engineer",
    "PU_Human-Covalex-Worker-Female-DistroHub_Storage": "Covalex Worker DistroHub Storage",
    "PU_Human-Covalex-Worker-Male-DistroHub_Engineer": "Covalex Worker DistroHub Engineer",
    "PU_Human-Covalex-Worker-Male-DistroHub_Storage": "Covalex Worker DistroHub Storage",
    "PU_Human-CryAstro-DeskWorker-Female-DistroHub": "CryAstro DeskWorker DistroHub",
    "PU_Human-CryAstro-DeskWorker-Male-DistroHub": "CryAstro DeskWorker DistroHub",
    "PU_Human-CryAstro-Worker-Female-DistroHub_Storage": "CryAstro Worker DistroHub Storage",
    "PU_Human-CryAstro-Worker-Male-DistroHub_Storage": "CryAstro Worker DistroHub Storage",
    "PU_Human-Greycat-DeskWorker-Female-DistroHub_Administrator": "Greycat DeskWorker DistroHub Administrator",
    "PU_Human-Greycat-DeskWorker-Female-DistroHub_OfficeWorker": "Greycat DeskWorker DistroHub OfficeWorker",
    "PU_Human-Greycat-DeskWorker-Male-DistroHub_Administrator": "Greycat DeskWorker DistroHub Administrator",
    "PU_Human-Greycat-DeskWorker-Male-DistroHub_OfficeWorker": "Greycat DeskWorker DistroHub OfficeWorker",
    "PU_Human-Greycat-Worker-Female-DistroHub_Engineer": "Greycat Worker DistroHub Engineer",
    "PU_Human-Greycat-Worker-Female-DistroHub_Storage": "Greycat Worker DistroHub Storage",
    "PU_Human-Greycat-Worker-Male-DistroHub_Engineer": "Greycat Worker DistroHub Engineer",
    "PU_Human-Greycat-Worker-Male-DistroHub_Storage": "Greycat Worker DistroHub Storage",
    "PU_Human-Hurston-DeskWorker-Female-DistroHub_Administrator": "Hurston DeskWorker DistroHub Administrator",
    "PU_Human-Hurston-DeskWorker-Female-DistroHub_Civilian": "Hurston DeskWorker DistroHub Civilian",
    "PU_Human-Hurston-DeskWorker-Female-DistroHub_OfficeWorker": "Hurston DeskWorker DistroHub OfficeWorker",
    "PU_Human-Hurston-DeskWorker-Female-DistroHub_Vendor": "Hurston DeskWorker DistroHub Vendor",
    "PU_Human-Hurston-DeskWorker-Male-DistroHub_Administrator": "Hurston DeskWorker DistroHub Administrator",
    "PU_Human-Hurston-DeskWorker-Male-DistroHub_Civilian": "Hurston DeskWorker DistroHub Civilian",
    "PU_Human-Hurston-DeskWorker-Male-DistroHub_OfficeWorker": "Hurston DeskWorker DistroHub OfficeWorker",
    "PU_Human-Hurston-DeskWorker-Male-DistroHub_Vendor": "Hurston DeskWorker DistroHub Vendor",
    "PU_Human-Hurston-Guard-Female-Heavy": "Hurston Guard Heavy",
    "PU_Human-Hurston-Guard-Female-Medium": "Hurston Guard Medium",
    "PU_Human-Hurston-Guard-Female-Medium_Elite": "Hurston Guard Medium Elite",
    "PU_Human-Hurston-Guard-Male-Grunt": "Hurston Guard Grunt",
    "PU_Human-Hurston-Guard-Male-Heavy": "Hurston Guard Heavy",
    "PU_Human-Hurston-Guard-Male-Medium": "Hurston Guard Medium",
    "PU_Human-Hurston-Guard-Male-Medium_Elite": "Hurston Guard Medium Elite",
    "PU_Human-Hurston-Worker-Female-DistroHub_Engineer": "Hurston Worker DistroHub Engineer",
    "PU_Human-Hurston-Worker-Female-DistroHub_Storage": "Hurston Worker DistroHub Storage",
    "PU_Human-Hurston-Worker-Male-DistroHub_Engineer": "Hurston Worker DistroHub Engineer",
    "PU_Human-Hurston-Worker-Male-DistroHub_Storage": "Hurston Worker DistroHub Storage",
    "PU_Human-SakuraSun-DeskWorker-Female-DistroHub_Administrator": "SakuraSun DeskWorker DistroHub Administrator",
    "PU_Human-SakuraSun-DeskWorker-Female-DistroHub_Civilian": "SakuraSun DeskWorker DistroHub Civilian",
    "PU_Human-SakuraSun-DeskWorker-Female-DistroHub_OfficeWorker": "SakuraSun DeskWorker DistroHub OfficeWorker",
    "PU_Human-SakuraSun-DeskWorker-Female-DistroHub_Vendor": "SakuraSun DeskWorker DistroHub Vendor",
    "PU_Human-SakuraSun-DeskWorker-Male-DistroHub_Administrator": "SakuraSun DeskWorker DistroHub Administrator",
    "PU_Human-SakuraSun-DeskWorker-Male-DistroHub_Civilian": "SakuraSun DeskWorker DistroHub Civilian",
    "PU_Human-SakuraSun-DeskWorker-Male-DistroHub_OfficeWorker": "SakuraSun DeskWorker DistroHub OfficeWorker",
    "PU_Human-SakuraSun-Worker-Female-DistroHub_Engineer": "SakuraSun Worker DistroHub Engineer",
    "PU_Human-SakuraSun-Worker-Female-DistroHub_Storage": "SakuraSun Worker DistroHub Storage",
    "PU_Human-SakuraSun-Worker-Male-DistroHub_Engineer": "SakuraSun Worker DistroHub Engineer",
    "PU_Human-SakuraSun-Worker-Male-DistroHub_Storage": "SakuraSun Worker DistroHub Storage",
    "PU_Human-Dusters-Civilian-Female": "Dusters Civilian Female",
    "PU_Human-Dusters-Civilian-Male": "Dusters Civilian Male",
    "PU_Human-Dusters-Engineer-Female": "Dusters Engineer Female",
    "PU_Human-Dusters-Engineer-Male": "Dusters Engineer Male",
    "PU_Human-Dusters-Grunt-Female-Heavy": "Dusters Grunt Heavy",
    "PU_Human-Dusters-Grunt-Female-Light": "Dusters Grunt Light",
    "PU_Human-Dusters-Grunt-Female-Medium": "Dusters Grunt Medium",
    "PU_Human-Dusters-Grunt-Male-Heavy": "Dusters Grunt Heavy",
    "PU_Human-Dusters-Grunt-Male-Light": "Dusters Grunt Light",
    "PU_Human-Dusters-Grunt-Male-Medium": "Dusters Grunt Medium",
    "PU_Human-Dusters-Shopkeeper-Female": "Dusters Shopkeeper Female",
    "PU_Human-Dusters-Shopkeeper-Male": "Dusters Shopkeeper Male",
    "PU_Human-Dusters-Worker-Female": "Dusters Worker Female",
    "PU_Human-Dusters-Worker-Male": "Dusters Worker Male",
    "PU_Human-FakeMicrotech-DeskWorker-Female-DistroHub_Back": "FakeMicrotech DeskWorker DistroHub Back",
    "PU_Human-FakeMicrotech-DeskWorker-Female-DistroHub_Front": "FakeMicrotech DeskWorker DistroHub Front",
    "PU_Human-FakeMicrotech-DeskWorker-Male-DistroHub_Back": "FakeMicrotech DeskWorker DistroHub Back",
    "PU_Human-FakeMicrotech-DeskWorker-Male-DistroHub_Front": "FakeMicrotech DeskWorker DistroHub Front",
    "PU_Human-FakeMicrotech-Worker-Female-DistroHub_Storage_Back": "FakeMicrotech Worker DistroHub Storage Back",
    "PU_Human-FakeMicrotech-Worker-Female-DistroHub_Storage_Front": "FakeMicrotech Worker DistroHub Storage Front",
    "PU_Human-FakeMicrotech-Worker-Male-DistroHub_Storage_Back": "FakeMicrotech Worker DistroHub Storage Back",
    "PU_Human-FakeMicrotech-Worker-Male-DistroHub_Storage_Front": "FakeMicrotech Worker DistroHub Storage Front",
    "PU_Human-Microtech-Civilians-Female-Greeter": "Microtech Civilian Greeter",
    "PU_Human-Microtech-DeskWorker-Female-DistroHub": "Microtech DeskWorker DistroHub",
    "PU_Human-Microtech-DeskWorker-Female-DistroHub_Civilian": "Microtech DeskWorker DistroHub Civilian",
    "PU_Human-Microtech-DeskWorker-Male-DistroHub": "Microtech DeskWorker DistroHub",
    "PU_Human-Microtech-DeskWorker-Male-DistroHub_Civilian": "Microtech DeskWorker DistroHub Civilian",
    "PU_Human-Microtech-Guard-Male-Grunt": "Microtech Guard Grunt",
    "PU_Human-Microtech-Guard-Female": "Microtech Guard Female",
    "PU_Human-Microtech-Guard-Male-Heavy": "Microtech Guard Heavy",
    "PU_Human-Microtech-Guard-Male-Heavy_Boss": "Microtech Guard Heavy Boss",
    "PU_Human-Microtech-Guard-Male-Light": "Microtech Guard Light",
    "PU_Human-Microtech-Guard-Male-Medium": "Microtech Guard Medium",
    "PU_Human-Microtech-Guard-Male": "Microtech Guard Male",
    "PU_Human-Microtech-Guard-Male_Shotgun": "Microtech Guard Shotgun",
    "PU_Human-Microtech-Gunner-Male-Light": "Microtech Gunner Light",
    "PU_Human-Microtech-Pilot-Male-Light": "Microtech Pilot Light",
    "PU_Human-Microtech-Worker-Female-DistroHub_Engineer": "Microtech Worker DistroHub Engineer",
    "PU_Human-Microtech-Worker-Female-DistroHub_Storage": "Microtech Worker DistroHub Storage",
    "PU_Human-Microtech-Worker-Male-DistroHub_Engineer": "Microtech Worker DistroHub Engineer",
    "PU_Human-Microtech-Worker-Male-DistroHub_Storage": "Microtech Worker DistroHub Storage",
    "PU_Human-NineTails-Boss-Male-Boss": "NineTails Boss",
    "PU_Human-NineTails-Boss-Male-Boss-Backpack": "NineTails Boss Backpack",
    "PU_Human-NineTails-Boss-Male-Boss-LootedBlac": "NineTails Boss LootedBlac",
    "PU_Human-NineTails-Boss-Male-Boss-LootedCru": "NineTails Boss LootedCru",
    "PU_Human-NineTails-Boss-Male-Boss-LootedHur": "NineTails Boss LootedHur",
    "PU_Human-NineTails-Boss-Male-Boss-LootedMT": "NineTails Boss LootedMT",
    "PU_Human-NineTails-SuperBoss-Male-ArtKelvin": "NineTails SuperBoss ArtKelvin",
    "PU_Human-NineTails-SuperBoss-Male-DevinMarcus": "NineTails SuperBoss DevinMarcus",
    "PU_Human-NineTails-SuperBoss-Male-MendoRen": "NineTails SuperBoss MendoRen",
    "PU_Human-NineTails-SuperBoss-Male-NolanAcker": "NineTails SuperBoss NolanAcker",
    "PU_Human-NineTails-SuperBoss-Male-RemyKettle": "NineTails SuperBoss RemyKettle",
    "PU_Human-NineTails-Grunt-Male-Grunt": "NineTails Grunt",
    "PU_Human-NineTails-Grunt-Male-Heavy": "NineTails Grunt Heavy",
    "PU_Human-NineTails-Grunt-Male-Light": "NineTails Grunt Light",
    "PU_Human-NineTails-Grunt-Male-Medium": "NineTails Grunt Medium",
    "PU_Human-NineTails-Guard-Male-GrimHex-Guard": "NineTails Guard GrimHex Guard",
    "PU_Human-NineTails-Guard-Male-GrimHex-Light": "NineTails Guard GrimHex Light",
    "PU_Human-NineTails-Gunner-Male-Light": "NineTails Gunner Light",
    "PU_Human-NineTails-Pilot-Female-Light": "NineTails Pilot Light",
    "PU_Human-NineTails-Pilot-Male-Light": "NineTails Pilot Light",
    "NPC_Archetypes-Female-Human-AdminOfficers-Orison-Admin_ChairmansClub": "AdminOfficers Orison Admin ChairmansClub",
    "NPC_Archetypes-Female-Human-Surgeon": "Surgeon",
    "NPC_Archetypes-Female-Human-AdminOfficers-Reststop-Admin_Cargo": "AdminOfficers Reststop Admin Cargo",
    "NPC_Archetypes-Female-Human-AdminOfficers-Reststop-Admin_Cargo_Corrupt": "AdminOfficers Reststop Admin Cargo Corrupt",
    "NPC_Archetypes-Female-Human-Civilians-Area18-Civilian_Area18": "Civilian Area18 Civilian",
    "NPC_Archetypes-Female-Human-Civilians-Area18-Doctor_Area18": "Civilian Area18 Doctor",
    "NPC_Archetypes-Female-Human-Civilians-Area18-Greeter_IONorth": "Civilian Area18 Greeter IONorth",
    "NPC_Archetypes-Female-Human-Civilians-Area18-Nurse_Area18": "Civilian Area18 Nurse",
    "NPC_Archetypes-Female-Human-Civilians-Area18-OffDuty_Military_Area18": "Civilian Area18 OffDuty Military",
    "NPC_Archetypes-Female-Human-Receptionist-Area18-Hospital": "Receptionist Area18 Hospital",
    "NPC_Archetypes-Female-Human-Receptionist-RestStop-Clinic": "Receptionist RestStop Clinic",
    "NPC_Archetypes-Female-Human-Receptionist-Lorville-Hospital": "Receptionist Lorville Hospital",
    "NPC_Archetypes-Female-Human-Civilians-Cave-Explorer_Cave": "Civilian Cave Explorer Cave",
    "NPC_Archetypes-Female-Human-Civilians-Cave-Explorer_Helmet_Cave": "Civilian Cave Explorer Helmet Cave",
    "NPC_Archetypes-Female-Human-Civilians-Cave-Miner_Cave": "Civilian Cave Miner Cave",
    "NPC_Archetypes-Female-Human-Civilians-Cave-Miner_Helmet_Cave": "Civilian Cave Miner Helmet Cave",
    "NPC_Archetypes-Female-Human-Civilians-GrimHex-Doctor_GrimHex": "Civilian GrimHex Doctor GrimHex",
    "NPC_Archetypes-Female-Human-Civilians-GrimHex-Nurse_GrimHex": "Civilian GrimHex Nurse GrimHex",
    "NPC_Archetypes-Female-Human-Civilians-GrimHex-Patron": "Civilian GrimHex Patron",
    "NPC_Archetypes-Female-Human-Civilians-Pyro-Civilian_Reststop": "Civilian Civilian",
    "NPC_Archetypes-Female-Human-Civilians-Lorville-BusinessDistrict": "Civilian Lorville BusinessDistrict",
    "NPC_Archetypes-Female-Human-Civilians-Lorville-Derelict_Lorville": "Civilian Lorville Derelict Lorville",
    "NPC_Archetypes-Female-Human-Civilians-Lorville-Doctor_Lorville": "Civilian Lorville Doctor Lorville",
    "NPC_Archetypes-Female-Human-Civilians-Lorville-Nurse_Lorville": "Civilian Lorville Nurse Lorville",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-ATC_NewBabbage": "Civilian New Babbage ATC",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Civilian_IAE": "Civilian New Babbage Civilian IAE",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Civilian_NewBabbage": "Civilian New Babbage Civilian",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-ClubKid_NewBabbage": "Civilian New Babbage ClubKid",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Doctor_NewBabbage": "Civilian New Babbage Doctor",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Fitness_NewBabbage": "Civilian New Babbage Fitness",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Investor_NewBabbage": "Civilian New Babbage Investor",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-NewBabbage_Cold_Factory_Worker": "Civilian New Babbage NewBabbage Cold Factory Worker",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-NewBabbage_Factory_Worker": "Civilian New Babbage NewBabbage Factory Worker",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Nurse_NewBabbage": "Civilian New Babbage Nurse",
    "NPC_Archetypes-Female-Human-Civilians-NewBabbage-Programmer_NewBabbage": "Civilian New Babbage Programmer",
    "NPC_Archetypes-Female-Human-Civilians-SAIC-Greeter_RowenaDulli": "Civilian SAIC Greeter RowenaDulli",
    "NPC_Archetypes-Female-Human-Receptionist-NewBabbage-Hospital": "Receptionist New Babbage Hospital",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Business_Orison": "Civilian Orison Business",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Civilian_Orison": "Civilian Orison Civilian",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Doctor_Orison": "Civilian Orison Doctor",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Hauler_Orison": "Civilian Orison Hauler",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Nurse_Orison": "Civilian Orison Nurse",
    "NPC_Archetypes-Female-Human-Civilians-Orison-Tourist_Orison": "Civilian Orison Tourist",
    "NPC_Archetypes-Female-Human-Mechanics-Orison-Cousin_Crows_Mechanic": "Mechanics Orison Cousin Crows Mechanic",
    "NPC_Archetypes-Female-Human-Civilians-Outpost-Outpost_Exterior_Trader": "Civilian Outpost Outpost Exterior Trader",
    "NPC_Archetypes-Female-Human-Civilians-Outpost-Outpost_Exterior_Worker": "Civilian Outpost Outpost Exterior Worker",
    "NPC_Archetypes-Female-Human-Civilians-Outpost-Outpost_Interior_Trader": "Civilian Outpost Outpost Interior Trader",
    "NPC_Archetypes-Female-Human-Civilians-Outpost-Outpost_Interior_Worker": "Civilian Outpost Outpost Interior Worker",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Civilian_Reststop": "Civilian Reststop Civilian",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Doctor_Reststop": "Civilian Reststop Doctor",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Hauler_Reststop": "Civilian Reststop Hauler",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Janitor_Reststop": "Civilian Reststop Janitor",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Nurse_Reststop": "Civilian Reststop Nurse",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Recipient_Reststop": "Civilian Reststop Recipient",
    "NPC_Archetypes-Female-Human-Civilians-Reststop-Sender_Reststop": "Civilian Reststop Sender",
    "NPC_Archetypes-Female-Human-Civilians-Stanton-ServiceProvider_Stanton": "Civilian Stanton ServiceProvider",
    "NPC_Archetypes-Female-Human-Civilians-Utilitarian-Drug_Cook_Utilitarian": "Civilian Utilitarian Drug Cook",
    "NPC_Archetypes-Female-Human-Civilians-DerelictSettlement": "Civilian DerelictSettlement",
    "NPC_Archetypes-Female-Human-Civilians-DerelictSettlement_BarPatron": "Civilian DerelictSettlement BarPatron",
    "NPC_Archetypes-Female-Human-Civilians-DerelictSettlement_Outcast_BarPatron": "Civilian DerelictSettlement Outcast BarPatron",
    "NPC_Archetypes-Female-Human-Engineers-Mission-890Jump_MaintenanceCrew": "Engineers Mission 890Jump MaintenanceCrew",
    "NPC_Archetypes-Female-Human-Engineers-NewBabbage-Technician_NewBabbage": "Engineers New Babbage Technician",
    "NPC_Archetypes-Female-Human-Mechanics-Outpost-Outpost_Interior_Mechanic": "Mechanics Outpost Outpost Interior Mechanic",
    "NPC_Archetypes-Female-Human-Mechanics-Reststop-HangarCrew": "Mechanics Reststop HangarCrew",
    "NPC_Archetypes-Female-Human-Civilians-Utilitarian-Technician_Utilitarian": "Civilian Utilitarian Technician",
    "NPC_Archetypes-Female-Human-TourGuide-FleetWeek_TourGiver": "TourGuide FleetWeek TourGiver",
    "NPC_Archetypes-Female-Human-Guards-Area18-FleetWeek_Military_Guard": "Area18 FleetWeek Military Guard",
    "NPC_Archetypes-Female-Human-Guards-Area18-IAE_Security_Guard": "Area18 IAE Security Guard",
    "NPC_Archetypes-Female-Human-Guards-Mission-890Jump_HiredSecurity": "Mission 890Jump HiredSecurity",
    "NPC_Archetypes-Female-Human-Guards-NewBabbage-MT_Protection_Services": "NewBabbage MT Protection Services",
    "NPC_Archetypes-Female-Human-Guards-Outpost-Outpost_Exterior_Guard": "Outpost Outpost Exterior Guard",
    "NPC_Archetypes-Female-Human-Greeter-SAIC_RowenaDulli": "Greeter SAIC RowenaDulli",
    "NPC_Archetypes-Female-Human-Pirate-Cave-Explorer_Helmet_Cave": "Pirate Cave Explorer Helmet Cave",
    "NPC_Archetypes-Female-Human-Pirate-Cave-Miner_Helmet_Cave": "Pirate Cave Miner Helmet Cave",
    "NPC_Archetypes-Female-Human-Admin-Reststop_ShipRental_Clerk": "Admin Reststop ShipRental Clerk",
    "NPC_Archetypes-Female-Human-AdminOfficers-Ezhab": "AdminOfficers Ezhab",
    "NPC_Archetypes-Female-Human-ShopKeeper-Aparelli_Clerk": "ShopKeeper Aparelli Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Area18-Pharmacy_Clerk": "ShopKeeper Area18 Pharmacy Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-NewBabbage-Pharmacy_Clerk": "ShopKeeper New Babbage Pharmacy Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Orison-Pharmacy_Clerk": "ShopKeeper Orison Pharmacy Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-CoffeeShop_Bartender": "ShopKeeper CoffeeShop Bartender",
    "NPC_Archetypes-Female-Human-ShopKeeper-CoffeeToGo_Bartender": "ShopKeeper CoffeeToGo Bartender",
    "NPC_Archetypes-Female-Human-ShopKeeper-Cousin_Crows_Shopkeeper": "ShopKeeper Cousin Crows Shopkeeper",
    "NPC_Archetypes-Female-Human-ShopKeeper-Crusader_Bartender": "ShopKeeper Crusader Bartender",
    "NPC_Archetypes-Female-Human-ShopKeeper-Derelict_Settlement_Vendor": "ShopKeeper Derelict Settlement Vendor",
    "NPC_Archetypes-Female-Human-ShopKeeper-EllroysCoffee_Bartender": "ShopKeeper EllroysCoffee Bartender",
    "NPC_Archetypes-Female-Human-ShopKeeper-Hawker": "ShopKeeper Hawker",
    "NPC_Archetypes-Female-Human-ShopKeeper-IAE_Barista": "ShopKeeper IAE Barista",
    "NPC_Archetypes-Female-Human-ShopKeeper-NewBabbage_Bureaucrat_Nest": "ShopKeeper New Babbage Bureaucrat Nest",
    "NPC_Archetypes-Female-Human-ShopKeeper-NewBabbage_FactoryLine_Clerk": "ShopKeeper New Babbage FactoryLine Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-OmegaPro_Clerk": "ShopKeeper OmegaPro Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Orison_Attendant_Dunlow": "ShopKeeper Orison Attendant Dunlow",
    "NPC_Archetypes-Female-Human-ShopKeeper-Orison_Attendant_GreenCircle": "ShopKeeper Orison Attendant GreenCircle",
    "NPC_Archetypes-Female-Human-ShopKeeper-Orison_GiftShop_Clerk": "ShopKeeper Orison GiftShop Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Reststop_Burrito_Clerk": "ShopKeeper Reststop Burrito Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Reststop_HotDog_Clerk": "ShopKeeper Reststop HotDog Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Reststop_Juice_Clerk": "ShopKeeper Reststop Juice Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Reststop_Noodle_Clerk": "ShopKeeper Reststop Noodle Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Reststop_Pizza_Clerk": "ShopKeeper Reststop Pizza Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Shopkeeper_3": "ShopKeeper Shopkeeper 3",
    "NPC_Archetypes-Female-Human-ShopKeeper-Shopkeeper_4": "ShopKeeper Shopkeeper 4",
    "NPC_Archetypes-Female-Human-ShopKeeper-Shopkeeper_5": "ShopKeeper Shopkeeper 5",
    "NPC_Archetypes-Female-Human-ShopKeeper-Shopkeeper_GC2": "ShopKeeper Shopkeeper GC2",
    "NPC_Archetypes-Female-Human-ShopKeeper-Traveler_Clerk": "ShopKeeper Traveler Clerk",
    "NPC_Archetypes-Female-Human-ShopKeeper-Voyager_Bartender": "ShopKeeper Voyager Bartender",
    "NPC_Archetypes-Female-Human-ShopKeeper-Whammers_Clerk": "ShopKeeper Whammers Clerk",
    "NPC_Archetypes-Male-Human-AdminOfficers-Area18-Admin_AdiraFalls": "AdminOfficers Area18 Admin AdiraFalls",
    "NPC_Archetypes-Male-Human-AdminOfficers-Area18-Admin_ArccorpDistro": "AdminOfficers Area18 Admin ArccorpDistro",
    "NPC_Archetypes-Male-Human-AdminOfficers-Area18-Admin_IONorth": "AdminOfficers Area18 Admin IONorth",
    "NPC_Archetypes-Male-Human-AdminOfficers-Area18-Admin_TDD": "AdminOfficers Area18 Admin TDD",
    "NPC_Archetypes-Male-Human-AdminOfficers-GrimHex-Admin_GrimHex": "AdminOfficers GrimHex Admin GrimHex",
    "NPC_Archetypes-Male-Human-AdminOfficers-Levski-Admin_Levski": "AdminOfficers Levski Admin Levski",
    "NPC_Archetypes-Male-Human-AdminOfficers-Lorville-Admin_Lorville": "AdminOfficers Lorville Admin Lorville",
    "NPC_Archetypes-Male-Human-AdminOfficers-NewBabbage-Admin_FTL": "AdminOfficers New Babbage Admin FTL",
    "NPC_Archetypes-Male-Human-AdminOfficers-NewBabbage-Admin_MTPlanetary": "AdminOfficers New Babbage Admin MTPlanetary",
    "NPC_Archetypes-Male-Human-AdminOfficers-NewBabbage-Admin_Shubin": "AdminOfficers New Babbage Admin Shubin",
    "NPC_Archetypes-Male-Human-AdminOfficers-NewBabbage-NewBabbage_TDD_Admin": "AdminOfficers New Babbage NewBabbage TDD Admin",
    "NPC_Archetypes-Male-Human-AdminOfficers-Ezhab": "AdminOfficers Ezhab",
    "NPC_Archetypes-Male-Human-AdminOfficers-Olisar-Admin_Olisar": "AdminOfficers Olisar Admin Olisar",
    "NPC_Archetypes-Male-Human-AdminOfficers-Orison-Admin_Covalex": "AdminOfficers Orison Admin Covalex",
    "NPC_Archetypes-Male-Human-AdminOfficers-Orison-Admin_FTL": "AdminOfficers Orison Admin FTL",
    "NPC_Archetypes-Male-Human-AdminOfficers-Outpost-Admin_Outpost": "AdminOfficers Outpost Admin Outpost",
    "NPC_Archetypes-Male-Human-AdminOfficers-Reststop-Admin_Cargo": "AdminOfficers Reststop Admin Cargo",
    "NPC_Archetypes-Male-Human-AdminOfficers-Reststop-Admin_Cargo_Corrupt": "AdminOfficers Reststop Admin Cargo Corrupt",
    "NPC_Archetypes-Male-Human-Civilians-Area18-ATC_Area18": "Civilian Area18 ATC",
    "NPC_Archetypes-Male-Human-Civilians-Area18-BarPatron_Area18": "Civilian Area18 BarPatron",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Bodyguard_Pacheco": "Civilian Area18 Bodyguard Pacheco",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Civilian_Area18": "Civilian Area18 Civilian",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Derelict_Homeless": "Civilian Area18 Derelict Homeless",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Derelict_Junkie": "Civilian Area18 Derelict Junkie",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Doctor_Area18": "Civilian Area18 Doctor",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Gang_A-1-8": "Civilian Area18 Gang A 1 8",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Gang_Devils": "Civilian Area18 Gang Devils",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Gang_LSM": "Civilian Area18 Gang LSM",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Greeter_Fleetweek": "Civilian Area18 Greeter Fleetweek",
    "NPC_Archetypes-Male-Human-Civilians-Area18-MedUnit_Area18": "Civilian Area18 MedUnit",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Nurse_Area18": "Civilian Area18 Nurse",
    "NPC_Archetypes-Male-Human-Civilians-Area18-OffDuty_Military_Area18": "Civilian Area18 OffDuty Military",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Pilot_Area18": "Civilian Area18 Pilot",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Tourist_Area18": "Civilian Area18 Tourist",
    "NPC_Archetypes-Male-Human-Civilians-Area18-Worker_DrugLab": "Civilian Area18 Worker DrugLab",
    "NPC_Archetypes-Male-Human-Civilians-GrabNGo-CoffeeShopPatron": "Civilian GrabNGo CoffeeShopPatron",
    "NPC_Archetypes-Male-Human-Civilians-Whammers-FoodShopPatron": "Civilian Whammers FoodShopPatron",
    "NPC_Archetypes-Male-Human-Surgeon": "Surgeon",
    "NPC_Archetypes-Male-Human-Civilians-Cave-Explorer_Cave": "Civilian Cave Explorer Cave",
    "NPC_Archetypes-Male-Human-Civilians-Cave-Explorer_Helmet_Cave": "Civilian Cave Explorer Helmet Cave",
    "NPC_Archetypes-Male-Human-Civilians-Cave-Miner_Cave": "Civilian Cave Miner Cave",
    "NPC_Archetypes-Male-Human-Civilians-Cave-Miner_Helmet_Cave": "Civilian Cave Miner Helmet Cave",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-BarPatron_GrimHex": "Civilian GrimHex BarPatron GrimHex",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-Civilian_GrimHex": "Civilian GrimHex Civilian GrimHex",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-Doctor_GrimHex": "Civilian GrimHex Doctor GrimHex",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-Nurse_GrimHex": "Civilian GrimHex Nurse GrimHex",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-Patron": "Civilian GrimHex Patron",
    "NPC_Archetypes-Male-Human-Civilians-GrimHex-RaceAnnouncer_NesCalloway": "Civilian GrimHex RaceAnnouncer NesCalloway",
    "NPC_Archetypes-Male-Human-Civilians-Pyro-Civilian_Reststop": "Civilian Civilian",
    "NPC_Archetypes-Male-Human-Civilians-Levski-BarPatron_Levski": "Civilian Levski BarPatron Levski",
    "NPC_Archetypes-Male-Human-Civilians-Levski-Civilian_Helmet_Levski": "Civilian Levski Civilian Helmet Levski",
    "NPC_Archetypes-Male-Human-Civilians-Levski-Civilian_Levski": "Civilian Levski Civilian Levski",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-ATC_Lorville": "Civilian Lorville ATC Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Central_Business_District": "Civilian Lorville Central Business District",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Civilian_Helmet_Lorville": "Civilian Lorville Civilian Helmet Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Civilian_Lorville": "Civilian Lorville Civilian Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Derelict_Lorville": "Civilian Lorville Derelict Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Doctor_Lorville": "Civilian Lorville Doctor Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Nurse_Lorville": "Civilian Lorville Nurse Lorville",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Patron": "Civilian Lorville Patron",
    "NPC_Archetypes-Male-Human-Civilians-Lorville-Worker_L19": "Civilian Lorville Worker L19",
    "NPC_Archetypes-Male-Human-Civilians-Mission-890Jump_Chef": "Civilian Mission 890Jump Chef",
    "NPC_Archetypes-Male-Human-Civilians-Mission-890Jump_FlightCrew": "Civilian Mission 890Jump FlightCrew",
    "NPC_Archetypes-Male-Human-Civilians-Mission-890Jump_PoolCleaner": "Civilian Mission 890Jump PoolCleaner",
    "NPC_Archetypes-Male-Human-Civilians-Mission-890Jump_VIP": "Civilian Mission 890Jump VIP",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Admin_RegalLuxuryRental_Template": "Civilian New Babbage Admin RegalLuxuryRental Template",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Admin_RegalLuxuryRental_1": "Civilian New Babbage Admin RegalLuxuryRental 1",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Admin_RegalLuxuryRental_2": "Civilian New Babbage Admin RegalLuxuryRental 2",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-BarPatron_NewBabbage": "Civilian New Babbage BarPatron",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Civilian_IAE": "Civilian New Babbage Civilian IAE",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Civilian_NewBabbage": "Civilian New Babbage Civilian",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Civilian_Wounded_Mission": "Civilian New Babbage Civilian Wounded Mission",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-ClubKid_NewBabbage": "Civilian New Babbage ClubKid",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-DJ_NewBabbage": "Civilian New Babbage DJ",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Doctor_NewBabbage": "Civilian New Babbage Doctor",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Fitness_NewBabbage": "Civilian New Babbage Fitness",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Investor_NewBabbage": "Civilian New Babbage Investor",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-NewBaggage_Cold_Factory_Worker": "Civilian New Babbage NewBaggage Cold Factory Worker",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-NewBaggage_Factory_Worker": "Civilian New Babbage NewBaggage Factory Worker",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-NewBaggage_Scientist": "Civilian New Babbage NewBaggage Scientist",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Nurse_NewBabbage": "Civilian New Babbage Nurse",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Programmer_NewBabbage": "Civilian New Babbage Programmer",
    "NPC_Archetypes-Male-Human-Civilians-NewBabbage-Tourist_NewBabbage": "Civilian New Babbage Tourist",
    "NPC_Archetypes-Male-Human-Receptionist-NewBabbage-Hospital": "Receptionist New Babbage Hospital",
    "NPC_Archetypes-Male-Human-Civilians-Olisar-Civilian_Helmet_Olisar": "Civilian Olisar Civilian Helmet Olisar",
    "NPC_Archetypes-Male-Human-Civilians-Olisar-Civilian_Olisar": "Civilian Olisar Civilian Olisar",
    "NPC_Archetypes-Male-Human-Civilians-Orison-ATC_Orison": "Civilian Orison ATC",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Business_Orison": "Civilian Orison Business",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Civilian_Orison": "Civilian Orison Civilian",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Doctor_Orison": "Civilian Orison Doctor",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Hauler_Orison": "Civilian Orison Hauler",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Nurse_Orison": "Civilian Orison Nurse",
    "NPC_Archetypes-Male-Human-Civilians-Orison-Tourist_Orison": "Civilian Orison Tourist",
    "NPC_Archetypes-Male-Human-Mechanics-Orison-Cousin_Crows_Mechanic": "Mechanics Orison Cousin Crows Mechanic",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Exterior_Trader": "Civilian Outpost Outpost Exterior Trader",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Exterior_Worker": "Civilian Outpost Outpost Exterior Worker",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Interior_Cook": "Civilian Outpost Outpost Interior Cook",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Interior_Trader": "Civilian Outpost Outpost Interior Trader",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Interior_Worker": "Civilian Outpost Outpost Interior Worker",
    "NPC_Archetypes-Male-Human-Civilians-Outpost-Outpost_Naked_Guy": "Civilian Outpost Outpost Naked Guy",
    "NPC_Archetypes_Male_Human_Civilians_Prisoner": "Civilian Prisoner",
    "NPC_Archetypes-Male-Human-Civilians-Refinery-Refinery_Foreman": "Civilian Refinery Refinery Foreman",
    "NPC_Archetypes-Male-Human-Civilians-Refinery-Refinery_Technician": "Civilian Refinery Refinery Technician",
    "NPC_Archetypes-Male-Human-Civilians-Refinery-Refinery_Worker": "Civilian Refinery Refinery Worker",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Civilian_Reststop": "Civilian Reststop Civilian",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Doctor_Reststop": "Civilian Reststop Doctor",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Hauler_Reststop": "Civilian Reststop Hauler",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Janitor_Reststop": "Civilian Reststop Janitor",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Nurse_Reststop": "Civilian Reststop Nurse",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Recipient_Reststop": "Civilian Reststop Recipient",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Sender_Reststop": "Civilian Reststop Sender",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Stevedore_Fixer_Reststop": "Civilian Reststop Stevedore Fixer",
    "NPC_Archetypes-Male-Human-Civilians-Reststop-Stevedore_Reststop": "Civilian Reststop Stevedore",
    "NPC_Archetypes-Male-Human-Civilians-Stanton-ServiceProvider_Stanton": "Civilian Stanton ServiceProvider",
    "NPC_Archetypes-Male-Human-Civilians-Utilitarian-Drug_Chief_Utilitarian": "Civilian Utilitarian Drug Chief",
    "NPC_Archetypes-Male-Human-Civilians-Utilitarian-Drug_Cook_Utilitarian": "Civilian Utilitarian Drug Cook",
    "NPC_Archetypes-Male-Human-Civilians-DerelictSettlement": "Civilian DerelictSettlement",
    "NPC_Archetypes-Male-Human-Civilians-DerelictSettlement_BarPatron": "Civilian DerelictSettlement BarPatron",
    "NPC_Archetypes-Male-Human-Customs-Area18-Customs_Clerk_Area18": "Customs Area18 Customs Clerk",
    "NPC_Archetypes-Male-Human-Engineers-Area18-Engineer_Area18": "Engineers Area18 Engineer",
    "NPC_Archetypes-Male-Human-Engineers-GrimHex-Engineer_GrimHex": "Engineers GrimHex Engineer GrimHex",
    "NPC_Male_Human_HangarMechanic_GrimHex": "HangarMechanic GrimHex",
    "Male-Human-Mechanic-Generic": "Male Mechanic Generic",
    "NPC_Archetypes-Male-Human-Engineers-Levski-Engineer_Levski": "Engineers Levski Engineer Levski",
    "NPC_Archetypes-Male-Human-Engineers-Lorville-Engineer_Lorville": "Engineers Lorville Engineer Lorville",
    "NPC_Archetypes-Male-Human-Engineers-Lorville-HangarCrew_Archimedes": "Engineers Lorville HangarCrew Archimedes",
    "NPC_Archetypes-Male-Human-Engineers-Lorville-HangarCrew_Indoor": "Engineers Lorville HangarCrew Indoor",
    "NPC_Archetypes-Male-Human-Engineers-Lorville-HangarCrew_Vacuum": "Engineers Lorville HangarCrew Vacuum",
    "NPC_Archetypes-Male-Human-Mechanics-Lorville-HangarCrew_Archimedes": "Mechanics Lorville HangarCrew Archimedes",
    "Male-Human-Engineer-Generic": "Male Engineer Generic",
    "NPC_Archetypes-Male-Human-Engineers-Mission-890Jump_MaintanenceCrew": "Engineers Mission 890Jump MaintanenceCrew",
    "NPC_Archetypes-Male-Human-Engineers-NewBabbage-Technician_NewBabbage": "Engineers New Babbage Technician",
    "NPC_Archetypes-Male-Human-Engineers-Olisar-Engineer_Olisar": "Engineers Olisar Engineer Olisar",
    "NPC_Archetypes-Male-Human-Mechanics-Outpost-Outpost_Interior_Mechanic": "Mechanics Outpost Outpost Interior Mechanic",
    "NPC_Archetypes-Male-Human-Engineers-Reststop-Engineer_Reststop": "Engineers Reststop Engineer",
    "NPC_Archetypes-Male-Human-Mechanics-Reststop-HangarCrew": "Mechanics Reststop HangarCrew",
    "NPC_Archetypes-Male-Human-Civilians-Utilitarian-Lab_Chief_Utilitarian": "Civilian Utilitarian Lab Chief",
    "NPC_Archetypes-Male-Human-Civilians-Utilitarian-Technician_Utilitarian": "Civilian Utilitarian Technician",
    "NPC_Archetypes-Male-Human-Civilians-Utilitarian-Technician_Utilitarian_08_XenoThreat": "Civilian Utilitarian Technician Utilitarian 08 XenoThreat",
    "NPC_Archetypes-Male-Human-Guards-FleetWeek_NavyGuard": "FleetWeek NavyGuard",
    "NPC_Archetypes-Male-Human-TourGuide-FleetWeek_TourGiver": "TourGuide FleetWeek TourGiver",
    "NPC_Archetypes-Male-Human-Generic_NPC-Centurion": "Generic NPC Centurion",
    "NPC_Archetypes-Male-Human-Generic_NPC-Generic_NPC": "Generic NPC Generic NPC",
    "NPC_Archetypes-Male-Human-Generic_NPC-Imperator": "Generic NPC Imperator",
    "NPC_Archetypes-Male-Human-Generic_NPC-Mannequin": "Generic NPC Mannequin",
    "NPC_Archetypes-Male-Human-Guards-Area18-FleetWeek_Military_Guard": "Area18 FleetWeek Military Guard",
    "NPC_Archetypes-Male-Human-Guards-Area18-FleetWeek_Security_Guard": "Area18 FleetWeek Security Guard",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_Area18": "Area18 Guard",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_AstroArmada": "Area18 Guard AstroArmada",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_BlacjacSecurity": "Area18 Guard BlacjacSecurity",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_BlacjacSecurity_Heavy": "Area18 Guard BlacjacSecurity Heavy",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_BlacjacSecurity_Light": "Area18 Guard BlacjacSecurity Light",
    "NPC_Archetypes-Male-Human-Guards-Area18-Guard_BlacjacSecurity_Medium": "Area18 Guard BlacjacSecurity Medium",
    "NPC_Archetypes-Human-Blacjac-Guard-Male-Heavy": "Blacjac Guard Heavy",
    "NPC_Archetypes-Male-Human-Guards_UGF_BlacjacSecurity_Boss": "UGF BlacjacSecurity Boss",
    "NPC_Archetypes-Male-Human-Guards_UGF_BlacjacSecurity_Light": "UGF BlacjacSecurity Light",
    "NPC_Archetypes-Male-Human-Guards_UGF_BlacjacSecurity_Medium": "UGF BlacjacSecurity Medium",
    "NPC_Archetypes-Male-Human-Guards-Levski-Guard_Levski": "Levski Guard Levski",
    "NPC_Archetypes-Male-Human-Guards-Hurston-Guard_Heavy": "Hurston Guard Heavy",
    "NPC_Archetypes-Male-Human-Guards-Hurston-Guard_Heavy_Boss": "Hurston Guard Heavy Boss",
    "NPC_Archetypes-Male-Human-Guards-Hurston-Guard_Light": "Hurston Guard Light",
    "NPC_Archetypes-Male-Human-Guards-Hurston-Guard_Medium": "Hurston Guard Medium",
    "NPC_Archetypes-Male-Human-Guards-Lorville-Guard_CBD": "Lorville Guard CBD",
    "NPC_Archetypes-Male-Human-Guards-Lorville-Guard_Lorville": "Lorville Guard Lorville",
    "NPC_Archetypes-Male-Human-Guards-Mission-890Jump_HiredSecurity": "Mission 890Jump HiredSecurity",
    "NPC_Archetypes-Male-Human-Guards-Mission-PrisonTransport_Shotgun": "Mission PrisonTransport Shotgun",
    "NPC_Archetypes-Male-Human-Guards-Olisar-Guard_Olisar": "Olisar Guard Olisar",
    "NPC_Archetypes-Male-Human-Guards-Outpost-Outpost_Exterior_Guard": "Outpost Outpost Exterior Guard",
    "NPC_Archetypes-Male-Human-Guards-Outpost-Outpost_Interior_Guard": "Outpost Outpost Interior Guard",
    "NPC_Archetypes-Male-Human-Guards-Prison-Guard": "Prison Guard",
    "NPC_Archetypes-Male-Human-Guards-Prison-Guard_Light": "Prison Guard Light",
    "NPC_Archetypes-Male-Human-Guards-Reststop-Guard_CargoDeck": "Reststop Guard CargoDeck",
    "NPC_Archetypes-Male-Human-Guards-Stanton-Advocacy_Agent": "Stanton Advocacy Agent",
    "NPC_Archetypes-Male-Human-Guards-Stanton-Navy_Heavy": "Stanton Navy Heavy",
    "NPC_Archetypes-Male-Human-Guards-Stanton-Navy_Light": "Stanton Navy Light",
    "NPC_Archetypes-Male-Human-Guards-Stanton-Navy_Medium": "Stanton Navy Medium",
    "NPC_Archetypes-Male-Human-Pirate-Cave-Explorer_Helmet_Cave": "Pirate Cave Explorer Helmet Cave",
    "NPC_Archetypes-Male-Human-Pirate-Cave-Miner_Helmet_Cave": "Pirate Cave Miner Helmet Cave",
    "NPC_Archetypes-Male-Human-distributioncentre": "distributioncentre",
    "NPC_Archetypes-Male-Human-Cheesecake": "Cheesecake",
    "NPC_Archetypes-Male-Human-Cheesecake_cqc": "Cheesecake CQC",
    "NPC_Archetypes-Male-Human-Cheesecake_juggernaut": "Cheesecake Juggernaut",
    "NPC_Archetypes-Male-Human-Cheesecake_juggernaut_cqc": "Cheesecake Juggernaut CQC",
    "NPC_Archetypes-Male-Human-Cheesecake_juggernaut_UnqiueTarget": "Cheesecake Juggernaut UnqiueTarget",
    "NPC_Archetypes-Male-Human-Cheesecake_Pilot": "Cheesecake Pilot",
    "NPC_Archetypes-Male-Human-Cheesecake_sniper": "Cheesecake Sniper",
    "NPC_Archetypes-Male-Human-Cheesecake_soldier": "Cheesecake Soldier",
    "NPC_Archetypes-Male-Human-Cheesecake_techie": "Cheesecake Techie",
    "NPC_Archetypes-Male-Human-distributioncentre_cqc": "DC CQC",
    "NPC_Archetypes-Male-Human-distributioncentre_juggernaut": "DC Juggernaut",
    "NPC_Archetypes-Male-Human-distributioncentre_juggernaut_cqc": "DC Juggernaut CQC",
    "NPC_Archetypes-Male-Human-distributioncentre_sniper": "DC Sniper",
    "NPC_Archetypes-Male-Human-distributioncentre_soldier": "DC Soldier",
    "NPC_Archetypes-Male-Human-distributioncentre_techie": "DC Techie",
    "NPC_Archetypes-Male-Human-Pirate-890Jump_ShipJacker_Medium": "Pirate 890Jump ShipJacker Medium",
    "NPC_Archetypes-Male-Human-Pirate-Bunker_Outlaw_Light": "Pirate Bunker Outlaw Light",
    "NPC_Archetypes-Male-Human-Pirate-Bunker_Outlaw_Medium": "Pirate Bunker Outlaw Medium",
    "NPC_Archetypes-Male-Human-Pirate-Bunker_Outlaw_Medium_Shotgun": "Pirate Bunker Outlaw Medium Shotgun",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Template": "Pirate Kareah Template",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Heavy": "Pirate Kareah Heavy",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Heavy": "Pirate Kareah Outlaw Heavy",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Heavy_Pistol": "Pirate Kareah Outlaw Heavy Pistol",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Heavy_Pistol_SMG": "Pirate Kareah Outlaw Heavy Pistol SMG",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Heavy_Shouldered": "Pirate Kareah Outlaw Heavy Shouldered",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Light": "Pirate Kareah Light",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Light": "Pirate Kareah Outlaw Light",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Light_Pistol": "Pirate Kareah Outlaw Light Pistol",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Light_Pistol_CitCon19": "Pirate Kareah Outlaw Light Pistol CitCon19",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Light_Pistol_NoHelmet": "Pirate Kareah Outlaw Light Pistol NoHelmet",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Medium": "Pirate Kareah Medium",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium": "Pirate Kareah Outlaw Medium",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium_NoHelmet": "Pirate Kareah Outlaw Medium NoHelmet",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium_Pistol_NoHelmet": "Pirate Kareah Outlaw Medium Pistol NoHelmet",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium_Shotgun": "Pirate Kareah Outlaw Medium Shotgun",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium_Shouldered": "Pirate Kareah Outlaw Medium Shouldered",
    "NPC_Archetypes-Male-Human-Pirate-Kareah_Outlaw_Medium_Shouldered_NoHelmet": "Pirate Kareah Outlaw Medium Shouldered NoHelmet",
    "NPC_Archetypes-Male-Human-Pirate-Pirate_Heavy": "Pirate Pirate Heavy",
    "NPC_Archetypes-Male-Human-Pirate-Pirate_Light": "Pirate Pirate Light",
    "NPC_Archetypes-Male-Human-Pirate-Pirate_Medium": "Pirate Pirate Medium",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Outlaw_Heavy": "Pirate Sand Outlaw Heavy",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Outlaw_Light": "Pirate Sand Outlaw Light",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Outlaw_Medium": "Pirate Sand Outlaw Medium",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Scavenger": "Pirate Sand Scavenger",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Slaver_Heavy": "Pirate Sand Slaver Heavy",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Slaver_Light": "Pirate Sand Slaver Light",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Slaver_Medium": "Pirate Sand Slaver Medium",
    "NPC_Archetypes-Male-Human-Pirate-Sand_Slaver_Undersuit": "Pirate Sand Slaver Undersuit",
    "NPC_Archetypes-Male-Human-Pirate-Xenothreat_Marine_Medium": "Pirate XenoThreat Marine Medium",
    "NPC_Archetypes-Male-Human-Admin-Reststop_CargoGuild_Rep": "Admin Reststop CargoGuild Rep",
    "NPC_Archetypes-Male-Human-Admin-Reststop_Container_Clerk": "Admin Reststop Container Clerk",
    "NPC_Archetypes-Male-Human-Admin-Reststop_ShipRental_Clerk": "Admin Reststop ShipRental Clerk",
    "NPC_Archetypes-Male-Human-Civilians-IAE-IAE_Tech_Staff": "Civilian IAE IAE Tech Staff",
    "NPC_Archetypes-Male-Human-ShopKeeper-Admin_1": "ShopKeeper Admin 1",
    "NPC_Archetypes-Male-Human-ShopKeeper-Admin_3": "ShopKeeper Admin 3",
    "NPC_Archetypes-Male-Human-ShopKeeper-Aparelli_Clerk": "ShopKeeper Aparelli Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Area18_BlackMarket": "ShopKeeper Area18 BlackMarket",
    "NPC_Archetypes-Male-Human-ShopKeeper-Area18_DrugDealer": "ShopKeeper Area18 DrugDealer",
    "NPC_Archetypes-Male-Human-ShopKeeper-Area18_Hawker": "ShopKeeper Area18 Hawker",
    "NPC_Archetypes-Male-Human-ShopKeeper-Armor_Clerk": "ShopKeeper Armor Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-AstroArmada_Clerk": "ShopKeeper AstroArmada Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Bartender": "ShopKeeper Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Casaba_Clerk": "ShopKeeper Casaba Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Centermass_Clerk": "ShopKeeper Centermass Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-CitCon_Dealer": "ShopKeeper CitCon Dealer",
    "NPC_Archetypes-Male-Human-ShopKeeper-Clor_Vee": "ShopKeeper Clor Vee",
    "NPC_Archetypes-Male-Human-ShopKeeper-CoffeeShop_Bartender": "ShopKeeper CoffeeShop Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Cousin_Crows_Shopkeeper": "ShopKeeper Cousin Crows Shopkeeper",
    "NPC_Archetypes-Male-Human-ShopKeeper-Crusader_Bartender": "ShopKeeper Crusader Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Customs_Clerk": "ShopKeeper Customs Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Derelict_Settlement_Bartender": "ShopKeeper Derelict Settlement Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Derelict_Settlement_Outcast_Bartender": "ShopKeeper Derelict Settlement Outcast Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Derelict_Settlement_Outcast_Vendor": "ShopKeeper Derelict Settlement Outcast Vendor",
    "NPC_Archetypes-Male-Human-ShopKeeper-Derelict_Settlement_Vendor": "ShopKeeper Derelict Settlement Vendor",
    "NPC_Archetypes-Male-Human-ShopKeeper-DrinksShop_Bartender": "ShopKeeper DrinksShop Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-DumpersDepot_Clerk": "ShopKeeper DumpersDepot Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-EllroysCoffee_Bartender": "ShopKeeper EllroysCoffee Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-GarciasGreens_Clerk": "ShopKeeper GarciasGreens Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-GLoc_Bartender": "ShopKeeper GLoc Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-GrimHex_Food_Vendor": "ShopKeeper GrimHex Food Vendor",
    "NPC_Archetypes-Male-Human-ShopKeeper-Hawker": "ShopKeeper Hawker",
    "NPC_Archetypes-Male-Human-ShopKeeper-IAE_Barista": "ShopKeeper IAE Barista",
    "NPC_Archetypes-Male-Human-ShopKeeper-KCTrending_Clerk": "ShopKeeper KCTrending Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-KelTo_Clerk": "ShopKeeper KelTo Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Lorville_Hab_Attendant": "ShopKeeper Lorville Hab Attendant",
    "NPC_Archetypes-Male-Human-ShopKeeper-Maintenance_Clerk": "ShopKeeper Maintenance Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Makau_Clerk": "ShopKeeper Makau Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Market_Clerk": "ShopKeeper Market Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Market_Clerk_limited": "ShopKeeper Market Clerk limited",
    "NPC_Archetypes-Male-Human-ShopKeeper-Medical_Clerk": "ShopKeeper Medical Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-MMHC_Bartender": "ShopKeeper MMHC Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-MMHC_Bouncer": "ShopKeeper MMHC Bouncer",
    "NPC_Archetypes-Male-Human-ShopKeeper-MV_Bartender": "ShopKeeper MV Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-NewBabbage_Bureaucrat_Nest": "ShopKeeper New Babbage Bureaucrat Nest",
    "NPC_Archetypes-Male-Human-ShopKeeper-NewBabbage_FactoryLine_Clerk": "ShopKeeper New Babbage FactoryLine Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-NewBabbage_GiftShop_Clerk": "ShopKeeper New Babbage GiftShop Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-NewDeal_Clerk": "ShopKeeper NewDeal Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-NoodleStand_Clerk": "ShopKeeper NoodleStand Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Outpost-Outpost_McGuffin_Vendor": "ShopKeeper Outpost Outpost McGuffin Vendor",
    "NPC_Archetypes-Male-Human-ShopKeeper-PersonalWeapons_Clerk": "ShopKeeper PersonalWeapons Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Providence_Surplus_Clerk": "ShopKeeper Providence Surplus Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Refinery_Foreman": "ShopKeeper Refinery Foreman",
    "NPC_Archetypes-Male-Human-ShopKeeper-Reststop_Burrito_Clerk": "ShopKeeper Reststop Burrito Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Reststop_HotDog_Clerk": "ShopKeeper Reststop HotDog Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Reststop_Juice_Clerk": "ShopKeeper Reststop Juice Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Reststop_Noodle_Clerk": "ShopKeeper Reststop Noodle Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Reststop_Pizza_Clerk": "ShopKeeper Reststop Pizza Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-SecondLifePawn_Clerk": "ShopKeeper SecondLifePawn Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-ShipDealer_Used_Clerk": "ShopKeeper ShipDealer Used Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-ShipParts_Clerk": "ShopKeeper ShipParts Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Skutters_Clerk": "ShopKeeper Skutters Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Tammany_Clerk": "ShopKeeper Tammany Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Teachs_Clerk": "ShopKeeper Teachs Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Traveler_Clerk": "ShopKeeper Traveler Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-TwynsSandwiches_Clerk": "ShopKeeper TwynsSandwiches Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-UEE_QuarterMaster": "ShopKeeper UEE QuarterMaster",
    "NPC_Archetypes-Male-Human-ShopKeeper-Voyager_Bartender": "ShopKeeper Voyager Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-WallysBar_Bartender": "ShopKeeper WallysBar Bartender",
    "NPC_Archetypes-Male-Human-ShopKeeper-Whammers_Clerk": "ShopKeeper Whammers Clerk",
    "NPC_Archetypes-Male-Human-ShopKeeper-Worker": "ShopKeeper Worker",
    "NPC_Archetypes-Female-Human-Receptionist-Grimhex-Hospital": "Receptionist Grimhex Hospital",
    "NPC_Archetypes-Female-Human-Receptionist-Orison-Hospital": "Receptionist Orison Hospital",
    "NPC_Archetypes-Male-Human-Receptionist-Orison-Hospital": "Receptionist Orison Hospital",
    "NPC_Archetypes_Female-Human-ArmedCivilian_Generic": "ArmedCivilian Generic",
    "NPC_Archetypes_Male-Human-ArmedCivilian_Generic": "ArmedCivilian Generic",
    "NPC_Archetypes_Male_Human_TourGuide": "TourGuide",
    "NPC_Archetype_Civilians": "Civilians",
    "NPC_Archetype_Civilians_Female": "Civilian Female",
    "NPC_Archetype_Civilians_Female_Crusader": "Civilian Crusader",
    "NPC_Archetype_Civilians_Female_Crusader_OrisonBusiness": "Civilian Crusader OrisonBusiness",
    "NPC_Archetype_Civilians_Male": "Civilian Male",
    "NPC_Archetype_Civilians_Male_Crusader": "Civilian Crusader",
    "NPC_Archetype_Civilians_Male_Crusader_OrisonBusiness": "Civilian Crusader OrisonBusiness",
    "PU_Human-Outlaw-DeskWorker-Female-Distrohub": "Outlaw DeskWorker Distrohub",
    "PU_Human-Outlaw-DeskWorker-Male-Distrohub": "Outlaw DeskWorker Distrohub",
    "PU_Human-Outlaw-Worker-Female-Distrohub_Storage": "Outlaw Worker Distrohub Storage",
    "PU_Human-Outlaw-Worker-Male-Distrohub_Storage": "Outlaw Worker Distrohub Storage",
    "PU_Human-Outlaw-Guard-Male-Heavy": "Outlaw Guard Heavy",
    "PU_Human-Outlaw-Guard-Male-Light": "Outlaw Guard Light",
    "PU_Human-Outlaw-Guard-Male-Medium": "Outlaw Guard Medium",
    "PU_Human-Bounty-Support-Male-Medium_Wounded_Mission": "Bounty Support Medium Wounded Mission",
    "PU_Human-Outlaw-Guard-Male-Unarmored": "Outlaw Guard Unarmored",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_cqc": "CitizensforProsperity CQC",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_juggernaut": "CitizensforProsperity Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_juggernaut_sentry": "CitizensforProsperity Juggernaut sentry",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_sniper": "CitizensforProsperity Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_soldier": "CitizensforProsperity Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_CitizensforProsperity_techie": "CitizensforProsperity Techie",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_captain": "CZ Captain",
    "PU_Human_Enemy_GroundCombat_NPC_contestedzones_cqc": "CZ CQC",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_grunt": "CZ Grunt",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_juggernaut": "CZ Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_sniper": "CZ Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_soldier": "CZ Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_Contestedzones_techie": "CZ Techie",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_cqc": "Headhunters CQC",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_juggernaut": "Headhunters Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_juggernaut_sentry": "Headhunters Juggernaut sentry",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_Pilot": "Headhunters Pilot",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_sniper": "Headhunters Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_soldier": "Headhunters Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_Headhunters_techie": "Headhunters Techie",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails": "Ninetails",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_cqc": "Ninetails CQC",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_grunt": "Ninetails Grunt",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_juggernaut": "Ninetails Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_sniper": "Ninetails Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_soldier": "Ninetails Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_Ninetails_techie": "Ninetails Techie",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_cqc": "Outlaw CQC",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_juggernaut": "Outlaw Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_juggernaut_sentry": "Outlaw Juggernaut sentry",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_sniper": "Outlaw Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_soldier": "Outlaw Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_pyro_outlaw_techie": "Outlaw Techie",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_cqc": "RoughAndReady CQC",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_juggernaut": "RoughAndReady Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_juggernaut_sentry": "RoughAndReady Juggernaut sentry",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_Sniper": "RoughAndReady Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_soldier": "RoughAndReady Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_RoughAndReady_techie": "RoughAndReady Techie",
    "PU_Human_Enemy_GroundCombat_NPC_Security_Lawful": "Security Lawful",
    "PU_Human_Enemy_GroundCombat_NPC_Security_Unlawful": "Security Unlawful",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_cqc": "XenoThreat CQC",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_juggernaut": "XenoThreat Juggernaut",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_juggernaut_sentry": "XenoThreat Juggernaut sentry",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_sniper": "XenoThreat Sniper",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_soldier": "XenoThreat Soldier",
    "PU_Human_Enemy_GroundCombat_NPC_xenothreat_techie": "XenoThreat Techie",
    "PU_Pilots-Human-BountyHunter-Gunner_Light": "BountyHunter Gunner Light",
    "PU_Pilots-Human-BountyHunter-Pilot_Light": "BountyHunter Pilot Light",
    "PU_Pilots-Human-Civilian-ARGO-Pilot-Lorville": "Civilian ARGO Pilot Lorville",
    "PU_Pilots-Human-Civilian-Gunner_Covalex": "Civilian Gunner Covalex",
    "PU_Pilots-Human-Civilian-Gunner_Explorer": "Civilian Gunner Explorer",
    "PU_Pilots-Human-Civilian-Gunner_Light": "Civilian Gunner Light",
    "PU_Pilots-Human-Civilian-Gunner_Light-CrimeStat": "Civilian Gunner Light CrimeStat",
    "PU_Pilots-Human-Civilian-Pilot_Covalex": "Civilian Pilot Covalex",
    "PU_Pilots-Human-Civilian-Pilot_Explorer": "Civilian Pilot Explorer",
    "PU_Pilots-Human-Civilian-Pilot_Light": "Civilian Pilot Light",
    "PU_Pilots-Human-Civilian-Pilot_Light-CrimeStat": "Civilian Pilot Light CrimeStat",
    "PU_Pilots-Human-Civilian-Pilot_Patrol": "Civilian Pilot Patrol",
    "PU_Pilots-Human-Criminal-Gunner_Light": "Criminal Gunner Light",
    "PU_Pilots-Human-Criminal-Pilot_Light": "Criminal Pilot Light",
    "PU_Human-Crusader-Gunner-Male-Light": "Crusader Gunner Light",
    "PU_Human-Crusader-Pilot-Male-Light": "Crusader Pilot Light",
    "PU_Pilots-Human-Advocacy-Gunner_Light": "Advocacy Gunner Light",
    "PU_Pilots-Human-Advocacy-Pilot_Light": "Advocacy Pilot Light",
    "PU_Pilots-Human-BlacJacSecurity-Gunner_Light": "BlacJacSecurity Gunner Light",
    "PU_Pilots-Human-BlacJacSecurity-Pilot_Light": "BlacJacSecurity Pilot Light",
    "PU_Pilots-Human-HurstonSecurity-Gunner_Light": "HurstonSecurity Gunner Light",
    "PU_Pilots-Human-HurstonSecurity-Pilot_Light": "HurstonSecurity Pilot Light",
    "PU_Pilots-Human-Navy-Gunner_Light": "Navy Gunner Light",
    "PU_Pilots-Human-Navy-Pilot_Light": "Navy Pilot Light",
    "PU_Pilots_Human_Advocacy_Pilot_Light_EA": "Advocacy Pilot Light EA",
    "PU_Pilots_Human_Supreme_Gunner_Light_EA": "Supreme Gunner Light EA",
    "PU_Pilots_Human_Supreme_Pilot_Light_EA": "Supreme Pilot Light EA",
    "PU_Pilots-Human-Hostile-Gunner": "Hostile Gunner",
    "PU_Pilots-Human-Hostile-Pilot": "Hostile Pilot",
    "PU_Pilots-Human-Pirate-Gunner_Light": "Pirate Gunner Light",
    "PU_Pilots-Human-Pirate-Pilot_Light": "Pirate Pilot Light",
    "PU_Pilots-Human-Pirate-Pilot_Light_MM": "Pirate Pilot Light MM",
    "PU_Pilots-Human-Navy-Fleetweek_Pilot_Light": "Navy Fleetweek Pilot Light",
    "PU_Pilots-Human-PrivateSecurity-Gunner_Light": "PrivateSecurity Gunner Light",
    "PU_Pilots-Human-PrivateSecurity-Pilot_Light": "PrivateSecurity Pilot Light",
    "PU_Pilots-Human-UEE-Gunner_Light": "UEE Gunner Light",
    "PU_Pilots-Human-UEE-Gunner_Light_NoDamage": "UEE Gunner Light NoDamage",
    "PU_Pilots-Human-UEE-Pilot_Invisible": "UEE Pilot Invisible",
    "PU_Pilots-Human-UEE-Pilot_Light": "UEE Pilot Light",
    "PU_Pilots-Human-UEE-Pilot_Light_MM": "UEE Pilot Light MM",
    "PU_Pilots-Human-UEE_Pilot_Light": "UEE Pilot Light",
    "PU_Pilots-Human-UEE_Pilot_Light_01_NoDamage": "UEE Pilot Light 01 NoDamage",
    "PU_Pilots-Vanduul-Gunner_Light": "Vanduul Gunner Light",
    "PU_Pilots-Vanduul-Pilot_Light": "Vanduul Pilot Light",
    "PU_Human-Criminal-Civilian-Female-Stanton": "Criminal Civilian",
    "PU_Human-Criminal-Civilian-Male-Stanton": "Criminal Civilian",
    "PU_Human-Criminal-Engineer-Female-Pyro": "Criminal Engineer",
    "PU_Human-Criminal-Engineer-Female-Stanton": "Criminal Engineer",
    "PU_Human-Criminal-Engineer-Male-Pyro": "Criminal Engineer",
    "PU_Human-Criminal-Engineer-Male-Stanton": "Criminal Engineer",
    "PU_Human-Criminal-Gardener-Male-Pyro": "Criminal Gardener",
    "PU_Human-Criminal-Guard-Female-Pyro-Heavy": "Criminal Guard Heavy",
    "PU_Human-Criminal-Guard-Female-Pyro-Light": "Criminal Guard Light",
    "PU_Human-Criminal-Guard-Female-Pyro-Medium": "Criminal Guard Medium",
    "PU_Human-Criminal-Guard-Female-Stanton-Heavy": "Criminal Guard Stanton Heavy",
    "PU_Human-Criminal-Guard-Female-Stanton-Light": "Criminal Guard Stanton Light",
    "PU_Human-Criminal-Guard-Female-Stanton-Medium": "Criminal Guard Stanton Medium",
    "PU_Human-Criminal-Guard-Male-Pyro-Heavy": "Criminal Guard Heavy",
    "PU_Human-Criminal-Guard-Male-Pyro-Heavy_01_Shotgun": "Criminal Guard Heavy 01 Shotgun",
    "PU_Human-Criminal-Guard-Male-Pyro-Heavy_Boss": "Criminal Guard Heavy Boss",
    "PU_Human-Criminal-Guard-Male-Pyro-Light": "Criminal Guard Light",
    "PU_Human-Criminal-Guard-Male-Pyro-Medium": "Criminal Guard Medium",
    "PU_Human-Criminal-Guard-Male-Pyro-Medium_01_Sentry": "Criminal Guard Medium 01 Sentry",
    "PU_Human-Criminal-Guard-Male-Pyro-Medium_Shotgun": "Criminal Guard Medium Shotgun",
    "PU_Human-Criminal-Guard-Male-Stanton-Heavy": "Criminal Guard Stanton Heavy",
    "PU_Human-Criminal-Guard-Male-Stanton-Light": "Criminal Guard Stanton Light",
    "PU_Human-Criminal-Guard-Male-Stanton-Medium": "Criminal Guard Stanton Medium",
    "PU_Human-Criminal-Shopkeeper-Female-Stanton": "Criminal Shopkeeper",
    "PU_Human-Criminal-Shopkeeper-Male-Stanton": "Criminal Shopkeeper",
    "PU_Human-Criminal-Worker-Female-Pyro": "Criminal Worker",
    "PU_Human-Criminal-Worker-Female-Stanton": "Criminal Worker",
    "PU_Human-Criminal-Worker-Male-Pyro": "Criminal Worker",
    "PU_Human-Criminal-Worker-Male-Stanton": "Criminal Worker",
    "PU_Human-Criminial-Prisoner-Female-Pyro": "Criminial Prisoner",
    "PU_Human-Criminial-Prisoner-Male-Pyro": "Criminial Prisoner",
    "PU_Human-Headhunter-Engineer-Female-Pyro": "Headhunter Engineer",
    "PU_Human-Headhunter-Engineer-Male-Pyro": "Headhunter Engineer",
    "PU_Human-Headhunter-Gardener-Female-Pyro": "Headhunter Gardener",
    "PU_Human-Headhunter-Gardener-Male-Pyro": "Headhunter Gardener",
    "PU_Human-Headhunter-Guard-Female-Pyro-Boss_01_Unbreathable": "Headhunter Guard Boss 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Female-Pyro-Heavy": "Headhunter Guard Heavy",
    "PU_Human-Headhunter-Guard-Female-Pyro-Heavy_01_Unbreathable": "Headhunter Guard Heavy 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Female-Pyro-Light": "Headhunter Guard Light",
    "PU_Human-Headhunter-Guard-Female-Pyro-Light_01_Unbreathable": "Headhunter Guard Light 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Female-Pyro-Medium": "Headhunter Guard Medium",
    "PU_Human-Headhunter-Guard-Female-Pyro-Medium_01_Unbreathable": "Headhunter Guard Medium 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Male-Pyro-Boss_01_Unbreathable": "Headhunter Guard Boss 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Male-Pyro-Heavy": "Headhunter Guard Heavy",
    "PU_Human-Headhunter-Guard-Male-Pyro-Heavy_01_Unbreathable": "Headhunter Guard Heavy 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Male-Pyro-Light": "Headhunter Guard Light",
    "PU_Human-Headhunter-Guard-Male-Pyro-Light_01_Unbreathable": "Headhunter Guard Light 01 Unbreathable",
    "PU_Human-Headhunter-Guard-Male-Pyro-Medium": "Headhunter Guard Medium",
    "PU_Human-Headhunter-Guard-Male-Pyro-Medium_01_Unbreathable": "Headhunter Guard Medium 01 Unbreathable",
    "PU_Human-Headhunter-Prisoner-Female-Pyro": "Headhunter Prisoner",
    "PU_Human-Headhunter-Prisoner-Male-Pyro": "Headhunter Prisoner",
    "PU_Human-Headhunter-Worker-Female-Pyro": "Headhunter Worker",
    "PU_Human-Headhunter-Worker-Male-Pyro": "Headhunter Worker",
    "PU_Human-Populace-Guard-Female-Stanton-MicroTech_MTProtechtionService": "Guard Stanton MicroTech MTProtechtionService",
    "PU_Human-Populace-Guard-Female-Stanton-Crusader-Kareah-CivilianGuard": "Guard Stanton Crusader Kareah CivilianGuard",
    "PU_Human-Populace-Guard-Female-Stanton-Crusader-Kareah_Light": "Guard Stanton Crusader Kareah Light",
    "PU_Human-Populace-Guard-Female-Stanton_Area18_Advocacy": "Guard Stanton Area18 Advocacy",
    "PU_Human-Populace-Guard-Female-Stanton_Area18_Astromada": "Guard Stanton Area18 Astromada",
    "PU_Human-Populace-Guard-Female-Stanton_Area18_BlacJac": "Guard Stanton Area18 BlacJac",
    "PU_Human-Populace-Guard-Female-Stanton_Area18_Guard": "Guard Stanton Area18 Guard",
    "PU_Human-Populace-Guard-Female-Stanton_Hurston_Lorville_HurstonSecurity": "Guard Stanton Hurston Lorville HurstonSecurity",
    "PU_Human-Populace-Guard-Female-Pyro-Frontier_Station_Heavy": "Guard Frontier Station Heavy",
    "PU_Human-Populace-Guard-Female-Pyro-Frontier_Station_Light": "Guard Frontier Station Light",
    "PU_Human-Populace-Guard-Female-Pyro-Frontier_Station_Medium": "Guard Frontier Station Medium",
    "PU_Human-Populace-Guard-Female-Pyro-Heavy": "Guard Heavy",
    "PU_Human-Populace-Guard-Female-Pyro-Light": "Guard Light",
    "PU_Human-Populace-Guard-Female-Pyro-Medium": "Guard Medium",
    "PU_Human-Populace-Guard-Male-Stanton-Area18_Advocacy": "Guard Stanton Area18 Advocacy",
    "PU_Human-Populace-Guard-Male-Stanton-Area18_Astromada": "Guard Stanton Area18 Astromada",
    "PU_Human-Populace-Guard-Male-Stanton-Area18_BlacJac": "Guard Stanton Area18 BlacJac",
    "PU_Human-Populace-Guard-Male-Stanton-Area18_Guard": "Guard Stanton Area18 Guard",
    "PU_Human-Populace-Guard-Male-Stanton-Crusader-Kareah-CivilianGuard": "Guard Stanton Crusader Kareah CivilianGuard",
    "PU_Human-Populace-Guard-Male-Stanton-Crusader-Kareah_Light": "Guard Stanton Crusader Kareah Light",
    "PU_Human-Populace-Guard-Male-Stanton-MicroTech-MTProtectionService": "Guard Stanton MicroTech MTProtectionService",
    "PU_Human-Populace-Guard-Male-Stanton_Hurston_Lorville_HurstonSecurity": "Guard Stanton Hurston Lorville HurstonSecurity",
    "PU_Human-Populace-Guard-Male-Pyro-Frontier_Station_Heavy": "Guard Frontier Station Heavy",
    "PU_Human-Populace-Guard-Male-Pyro-Frontier_Station_Light": "Guard Frontier Station Light",
    "PU_Human-Populace-Guard-Male-Pyro-Frontier_Station_Medium": "Guard Frontier Station Medium",
    "PU_Human-Populace-Guard-Male-Pyro-Heavy": "Guard Heavy",
    "PU_Human-Populace-Guard-Male-Pyro-Light": "Guard Light",
    "PU_Human-Populace-Guard-Male-Pyro-Medium": "Guard Medium",
    "PU_Human-Populace-Mechanic-Female-Lorville-HangarCrew": "Mechanic Lorville HangarCrew",
    "PU_Human-Populace-Mechanic-Female-Orison-Mechanic": "Mechanic Orison Mechanic",
    "PU_Human-Populace-Mechanic-Female-Orison-Mechanic-CousinCrow": "Mechanic Orison Mechanic CousinCrow",
    "PU_Human-Populace-Mechanic-Male-Lorville-HangarCrew": "Mechanic Lorville HangarCrew",
    "PU_Human-Populace-Mechanic-Male-Orison-Mechanic": "Mechanic Orison Mechanic",
    "PU_Human-Populace-Mechanic-Male-Orison-Mechanic-CousinCrow": "Mechanic Orison Mechanic CousinCrow",
    "PU_Human-Populace-Civilian-Female-Area18-Civilian": "Civilian Area18 Civilian",
    "PU_Human-Populace-Civilian-Female-Area18-Fleetweek_Civilian": "Civilian Area18 Fleetweek Civilian",
    "PU_Human-Populace-Civilian-Female-Area18-Fleetweek_Tourist": "Civilian Area18 Fleetweek Tourist",
    "PU_Human-Populace-Civilian-Female-Area18-Gang": "Civilian Area18 Gang",
    "PU_Human-Populace-Civilian-Female-Lorville-BusinessDistrict": "Civilian Lorville BusinessDistrict",
    "PU_Human-Populace-Civilian-Female-Lorville-Civilian": "Civilian Lorville Civilian",
    "PU_Human-Populace-Civilian-Female-NewBabbage-Business": "Civilian New Babbage Business",
    "PU_Human-Populace-Civilian-Female-NewBabbage-ClubKid": "Civilian New Babbage ClubKid",
    "PU_Human-Populace-Civilian-Female-NewBabbage-Scientist": "Civilian New Babbage Scientist",
    "PU_Human-Populace-Civilian-Female-NewBabbage-WhiteCollar": "Civilian New Babbage WhiteCollar",
    "PU_Human-Populace-Civilian-Female-NewBabbage": "Civilian",
    "PU_Human-Populace-Civilian-Female-Orison-Business": "Civilian Orison Business",
    "PU_Human-Populace-Civilian-Female-Orison-Civilian": "Civilian Orison Civilian",
    "PU_Human-Populace-Civilian-Female-Pyro-Frontier": "Civilian Frontier",
    "PU_Human-Populace-Civilian-Male-Area18-Fleetweek_Civilian": "Civilian Area18 Fleetweek Civilian",
    "PU_Human-Populace-Civilian-Male-Area18-Fleetweek_Tourist": "Civilian Area18 Fleetweek Tourist",
    "PU_Human-Populace-Civilian-Male-Area18-Civilian": "Civilian Area18 Civilian",
    "PU_Human-Populace-Civilian-Male-Area18-Gang": "Civilian Area18 Gang",
    "PU_Human-Populace-Civilian-Male-Lorville-BusinessDistrict": "Civilian Lorville BusinessDistrict",
    "PU_Human-Populace-Civilian-Male-Lorville-Civilian": "Civilian Lorville Civilian",
    "PU_Human-Populace-Civilian-Male-NewBabbage-Business": "Civilian New Babbage Business",
    "PU_Human-Populace-Civilian-Male-NewBabbage-ClubKid": "Civilian New Babbage ClubKid",
    "PU_Human-Populace-Civilian-Male-NewBabbage-Scientist": "Civilian New Babbage Scientist",
    "PU_Human-Populace-Civilian-Male-NewBabbage-WhiteColar": "Civilian New Babbage WhiteColar",
    "PU_Human-Populace-Civilian-Male-NewBabbage": "Civilian",
    "PU_Human-Populace-Civilian-Male-Orison-Business": "Civilian Orison Business",
    "PU_Human-Populace-Civilian-Male-Orison-Civilian": "Civilian Orison Civilian",
    "PU_Human-Populace-Civilian-Male-Pyro-Frontier": "Civilian Frontier",
    "PU_Human-Populace-Engineer-Female-Area18-Engineer": "Engineer Area18 Engineer",
    "PU_Human-Populace-Engineer-Female-Lorville-Engineer": "Engineer Lorville Engineer",
    "PU_Human-Frontier-Engineer-Female-Pyro": "Frontier Engineer",
    "PU_Human-Populace-Engineer-Female-CitizenForProsperity": "Engineer CitizenForProsperity",
    "PU_Human-Populace-Engineer-Female-Orison-Engineer": "Engineer Orison Engineer",
    "PU_Human-Populace-Engineer-Female-Pyro-Frontier": "Engineer Frontier",
    "PU_Human-Populace-Engineer-Female-Pyro-Frontier_01_Unbreathable": "Engineer Frontier 01 Unbreathable",
    "PU_Human-Populace-Engineer-Female-Pyro-Frontier_Station": "Engineer Frontier Station",
    "PU_Human-Populace-Engineer-Male-Area18-Engineer": "Engineer Area18 Engineer",
    "PU_Human-Populace-Engineer-Male-Lorville-Engineer": "Engineer Lorville Engineer",
    "PU_Human-Populace-Engineer-Male-Orison-Engineer": "Engineer Orison Engineer",
    "PU_Human-Frontier-Engineer-Male-Pyro": "Frontier Engineer",
    "PU_Human-Populace-Engineer-Male-CitizenForProsperity": "Engineer CitizenForProsperity",
    "PU_Human-Populace-Engineer-Male-Pyro-Frontier": "Engineer Frontier",
    "PU_Human-Populace-Engineer-Male-Pyro-Frontier_01_Unbreathable": "Engineer Frontier 01 Unbreathable",
    "PU_Human-Populace-Engineer-Male-Pyro-Frontier_Station": "Engineer Frontier Station",
    "PU_Human-Populace-Farmer-Female-CitizenForProsperity": "Farmer CitizenForProsperity",
    "PU_Human-Populace-Farmer-Female-Pyro-Frontier": "Farmer Frontier",
    "PU_Human-Populace-Farmer-Male-CitizenForProsperity": "Farmer CitizenForProsperity",
    "PU_Human-Populace-Farmer-Male-Pyro-Frontier": "Farmer Frontier",
    "PU_Human-Populace-Farmer-Male-Pyro-Frontier_01_Unbreathable": "Farmer Frontier 01 Unbreathable",
    "PU_Human-Frontier-Gardener-Male-Pyro": "Frontier Gardener",
    "PU_Human-Populace-Homeless-Female-Lorville-Derelict": "Homeless Lorville Derelict",
    "PU_Human-Populace-Homeless-Female-Pyro": "Homeless",
    "PU_Human-Populace-Homeless-Male-Lorville-Derelict": "Homeless Lorville Derelict",
    "PU_Human-Populace-Homeless-Male-Pyro": "Homeless",
    "PU_Human-Populace-Junkies-Female-Pyro": "Junkies",
    "PU_Human-Populace-Junkies-Male-Pyro": "Junkies",
    "PU_Human-Populace-Medical_Personnel-Female-Lorville-Doctor": "Medical Personnel Lorville Doctor",
    "PU_Human-Populace-Medical_Personnel-Female-Lorville-Surgeon": "Medical Personnel Lorville Surgeon",
    "PU_Human-Populace-Medical_Personnel-Female-Lorville-Nurse": "Medical Personnel Lorville Nurse",
    "PU_Human-Populace-Medical_Personnel-Female-Pyro-Frontier": "Medical Personnel Frontier",
    "PU_Human-Populace-Medical_Personnel-Male-Lorville-Doctor": "Medical Personnel Lorville Doctor",
    "PU_Human-Populace-Medical_Personnel-Male-Lorville-Surgeon": "Medical Personnel Lorville Surgeon",
    "PU_Human-Populace-Medical_Personnel-Male-Lorville-Nurse": "Medical Personnel Lorville Nurse",
    "PU_Human-Populace-Medical_Personnel-Male-Pyro-Frontier": "Medical Personnel Frontier",
    "PU_Human-Populace-Miner-Female-Pyro": "Miner",
    "PU_Human-Populace-Miner-Male-Pyro": "Miner",
    "PU_Human-Populace-Scavenger-Female-Pyro": "Scavenger",
    "PU_Human-Populace-Scavenger-Male-Pyro": "Scavenger",
    "PU_Human-Populace-Shopkeeper-Female-CitizenForProsperity": "Shopkeeper CitizenForProsperity",
    "PU_Human-Populace-Shopkeeper-Female-Pyro": "Shopkeeper",
    "PU_Human-Populace-Shopkeeper-Bartender-Female-Pyro": "Shopkeeper Bartender",
    "PU_Human-Populace-Shopkeeper-RetailVendor-Female-Pyro": "Shopkeeper RetailVendor",
    "PU_Human-Populace-Shopkeeper-StallVendor-Female-Pyro": "Shopkeeper StallVendor",
    "PU_Human-Populace-Shopkeeper-Vendor-Female-Pyro": "Shopkeeper Vendor",
    "PU_Human-Populace-Shopkeeper-Male-CitizenForProsperity": "Shopkeeper CitizenForProsperity",
    "PU_Human-Populace-Shopkeeper-Male-Pyro": "Shopkeeper",
    "PU_Human-Populace-Shopkeeper-Admin-Male-Pyro_1": "Shopkeeper Admin 1",
    "PU_Human-Populace-Shopkeeper-Bartender-Male-Pyro": "Shopkeeper Bartender",
    "PU_Human-Populace-Shopkeeper-RetailVendor-Male-Pyro": "Shopkeeper RetailVendor",
    "PU_Human-Populace-Shopkeeper-ShipDealer-Male-Pyro": "Shopkeeper ShipDealer",
    "PU_Human-Populace-Shopkeeper-StallVendor-Male-Pyro": "Shopkeeper StallVendor",
    "PU_Human-Populace-Shopkeeper-Vendor-Male-Pyro": "Shopkeeper Vendor",
    "PU_Human-Populace-Worker-Female-Lorville-L19_Worker": "Worker Lorville L19 Worker",
    "PU_Human-Frontier-Worker-Female-Pyro": "Frontier Worker",
    "PU_Human-Populace-Worker-Female-Pyro-Frontier_Station": "Worker Frontier Station",
    "PU_Human-Populace-Worker-Male-Lorville-L19_Worker": "Worker Lorville L19 Worker",
    "PU_Human-Frontier-Worker-Male-Pyro": "Frontier Worker",
    "PU_Human-Populace-Worker-Male-Pyro-Frontier_Station": "Worker Frontier Station",
    "PU_Human-RoughAndReady-Engineer-Female-Pyro": "RoughAndReady Engineer",
    "PU_Human-RoughAndReady-Engineer-Male-Pyro": "RoughAndReady Engineer",
    "PU_Human-RoughAndReady-Gangster-Female-Pyro": "RoughAndReady Gangster",
    "PU_Human-RoughAndReady-Gangster-Male-Pyro": "RoughAndReady Gangster",
    "PU_Human-RoughAndReady-Gardener-Female-Pyro": "RoughAndReady Gardener",
    "PU_Human-RoughAndReady-Gardener-Male-Pyro": "RoughAndReady Gardener",
    "PU_Human-RoughAndReady-Guard-Female-Pyro-Heavy": "RoughAndReady Guard Heavy",
    "PU_Human-RoughAndReady-Guard-Female-Pyro-Light": "RoughAndReady Guard Light",
    "PU_Human-RoughAndReady-Guard-Female-Pyro-Medium": "RoughAndReady Guard Medium",
    "PU_Human-RoughAndReady-Guard-Male-Pyro-Heavy": "RoughAndReady Guard Heavy",
    "PU_Human-RoughAndReady-Guard-Male-Pyro-Light": "RoughAndReady Guard Light",
    "PU_Human-RoughAndReady-Guard-Male-Pyro-Medium": "RoughAndReady Guard Medium",
    "PU_Human-RoughAndReady-Worker-Female-Pyro": "RoughAndReady Worker",
    "PU_Human-RoughAndReady-Worker-Male-Pyro": "RoughAndReady Worker",
    "Quadruped": "Quadruped",
    "Aloprat": "Aloprat",
    "Kopion": "Kopion",
    "Kopion_Cave": "Kopion Cave",
    "Kopion_cheescake_pet": "Kopion cheescake pet",
    "Kopion_Headhunter_pet": "Kopion Headhunter pet",
    "Kopion_Forest": "Kopion Forest",
    "Kopion_Savannah": "Kopion Savannah",
    "Kopion_Tundra": "Kopion Tundra",
    "Quasigrazer": "Quasigrazer",
    "Quasigrazer_Boreal": "Quasigrazer Boreal",
    "Quasigrazer_Grassland": "Quasigrazer Grassland",
    "Quasigrazer_Jungle": "Quasigrazer Jungle",
    "Quasigrazer_Tundra": "Quasigrazer Tundra",
    "Quasigrazer_Tundra_M": "Quasigrazer Tundra M",
    "HumanGeneric": "HumanGeneric",
    "HumanGeneric_Instanced": "HumanGeneric Instanced",
    "NPC_Human_Female_Generic": "Generic",
    "NPC_Human_Male_Generic": "Generic",
    "Player_Human_Female_Generic": "Player Generic",
    "Player_Human_Male_Generic": "Player Generic",
    "Transport": "Transport",
    "PowerSuit": "PowerSuit",
    "ARGO_ATLS": "ARGO ATLS",
    "ARGO_ATLS_GEO": "ARGO ATLS GEO",
    "vlk": "Valakkar",
    "vlk_juvenile": "Valakkar juvenile",
    "vlk_juvenile_sentry": "Valakkar juvenile sentry",
    "PU_Human-Xenothreat-SuperBoss-Male-Xenothreat_Commander": "XenoThreat SuperBoss XenoThreat Commander",
    "PU_Human-Xenothreat-Engineer-Female-Militia": "XenoThreat Engineer Militia",
    "PU_Human-Xenothreat-Engineer-Male-Militia": "XenoThreat Engineer Militia",
    "PU_Human-Xenothreat-Farmer-Female-Militia": "XenoThreat Farmer Militia",
    "PU_Human-Xenothreat-Farmer-Male-Militia": "XenoThreat Farmer Militia",
    "PU_Human-Xenothreat-Grunt-Male-Heavy": "XenoThreat Grunt Heavy",
    "PU_Human-Xenothreat-Grunt-Male-Heavy_01_CQC": "XenoThreat Grunt Heavy 01 CQC",
    "PU_Human-Xenothreat-Grunt-Male-Heavy_01_Gunner": "XenoThreat Grunt Heavy 01 Gunner",
    "PU_Human-Xenothreat-Grunt-Male-Heavy_01_Sniper": "XenoThreat Grunt Heavy 01 Sniper",
    "PU_Human-Xenothreat-Grunt-Male-Heavy_01_Soldier": "XenoThreat Grunt Heavy 01 Soldier",
    "PU_Human-Xenothreat-Grunt-Male-Light": "XenoThreat Grunt Light",
    "PU_Human-Xenothreat-Grunt-Male-Medium": "XenoThreat Grunt Medium",
    "PU_Human-Xenothreat-Grunt-Male-Medium_01_CQC": "XenoThreat Grunt Medium 01 CQC",
    "PU_Human-Xenothreat-Grunt-Male-Medium_01_Sniper": "XenoThreat Grunt Medium 01 Sniper",
    "PU_Human-Xenothreat-Grunt-Male-Medium_01_Soldier": "XenoThreat Grunt Medium 01 Soldier",
    "PU_Human-Xenothreat-Gunner-Male-Light": "XenoThreat Gunner Light",
    "PU_Human-Xenothreat-Pilot-Male-Light": "XenoThreat Pilot Light",
}
